# Generated by Django 4.2.6 on 2023-10-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_taskassigneemapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assignee',
        ),
    ]
