# Generated by Django 4.2.6 on 2023-10-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigneemapping',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='task_manager.customuser'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to='task_manager.customuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
